# -*- coding: utf-8 -*-
"""House_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_PFKv6x_ynWzPdrkG9WSUWRnvUuBN7P5
"""

import pandas as pd
import sys
import os
import requests

if __name__ == '__main__':
  if not os.path.exists('../Data'):
    os.mkdir('../Data')

if 'house_class.csv' not in os.listdir('../Data'):
  sys.stderr.write("[INFO] Dataset is loading.\n")
  url = "https://www.dropbox.com/s/7vjkrlggmvr5bc1/house_class.scv?dl=1"
  r = requests.get(url, allow_redirects=True)
  open('../Data/house_class.csv', 'wb').write(r.content)
  sys.stderr.write("[INFO] Loaded. \n")

df = pd.read_csv('../Data/house_class.csv')
print(f'''{df.shape[0]}
{df.shape[1]}
{df.isna().any().sum() != 0}
{df.Room.max()}
{df.Area.mean()}
{df.Zip_loc.nunique()}''')

